delete: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/delete.yaml
confirmDeletion: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/confirmDeletion.yaml
addConfigDefinition:
  dialogName: magnolia-auto-config-updates:components/configDefinitionDetail
  label: Add Config Definition
  icon: icon-add-item
  nodeType: config-definition
  class: info.magnolia.ui.framework.action.OpenCreateDialogActionDefinition
  availability:
    multiple: false
    root: true
    rules:
    - name: IsNotDeletedRule
      implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
editConfigDefinition:
  dialogName: magnolia-auto-config-updates:components/configDefinitionDetail
  label: Edit Config Definition
  icon: icon-edit
  class: info.magnolia.ui.framework.action.OpenEditDialogActionDefinition
  nodeType: config-definition
  availability:
    nodeTypes:
      config-definition: config-definition
    multiple: false
    root: false
    rules:
    - name: IsNotDeletedRule
      implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
# TO-DO
#
#
#runConfigChecks:
#  command: runConfigChecks
#  icon: icon-redo
#  class: com.netcetera.data.RunConfigurationChecksActionDefinition
#  availability:
#    root: true
#import:
#  icon: icon-import
#  dialogName: magnolia-auto-config-updates:components/importConfigChecks
#  class: info.magnolia.ui.framework.action.OpenCreateDialogActionDefinition
#  availability:
#    multiple: false
#    writePermissionRequired: true
#    root: true
#    rules:
#    - name: IsNotDeletedRule
#      implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
