label: Definitions
subAppClass: info.magnolia.ui.contentapp.browser.BrowserSubApp
class: info.magnolia.ui.contentapp.browser.BrowserSubAppDescriptor
closable: false
workbench: !include:/magnolia-auto-config-updates/apps-common/config-checks/workbench-definition-definition.yaml
contentConnector:
  workspace: advancedConfigUpdates
  defaultOrder: jcrName
  rootPath: /definition
  nodeTypes:
  - icon: icon-file-webpage
    name: definition
actions: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/definitionActions.yaml
actionbar: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/definitionActionbar.yaml