label: Emails
subAppClass: info.magnolia.ui.contentapp.browser.BrowserSubApp
class: info.magnolia.ui.contentapp.browser.BrowserSubAppDescriptor
closable: false
workbench: !include:/magnolia-auto-config-updates/apps-common/config-checks/workbench-definition-email.yaml
contentConnector:
  workspace: advancedConfigUpdates
  defaultOrder: jcrName
  rootPath: /email
  nodeTypes:
  - icon: icon-file-webpage
    name: email
actions: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/emailActions.yaml
actionbar: !include:/magnolia-auto-config-updates/apps-common/config-checks/subApps/actions/emailActionbar.yaml